# Generated by Django 4.1.3 on 2022-11-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                ("bio", models.TextField()),
                ("twitter", models.CharField(max_length=100)),
                ("instagram", models.CharField(max_length=100)),
                ("tiktok", models.CharField(max_length=100)),
                ("creator_nickname", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("volume", models.IntegerField(default=0)),
                ("quantity_sold", models.IntegerField(default=0)),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
