# Generated by Django 4.1.3 on 2022-11-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creators", "0002_alter_creator_bio_alter_creator_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
    ]
