# Generated by Django 4.1.3 on 2022-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
