# Generated by Django 4.1.3 on 2022-11-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0002_alter_nft_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="image",
            field=models.ImageField(max_length=255, upload_to="images/"),
        ),
    ]
